In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.compose import ColumnTransformer

#sklearn = module qui permet le ML. On peut aussi faire l'import au fur et à mesure

In [37]:
path_to_file="D:/Profils/NLefort/Desktop/JEDHA"

df=pd.read_csv(path_to_file+"/Data.csv")

df.head()

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes


On veut prédire le comportement d'achat

# Etape 3 : Feagure/traget split


In [38]:
#Je veux toutes les lignes et toutes les colonnes.
#soit je lis [:,0:4] --> en allant de gauche à droite. ou alors [:,:-1] pour dire que je lis de droite à gauche en incluant toutes les colonnes

"""Méthode 1
x=df.iloc[:,:-1]
#je veux colonne -1 en incluant le dataframe
y=df.iloc[:, -1:]
"""
"""Méthode 2"""
x=df.loc[:, ["Country", "Age", "Salary"]]
y=df.loc[:, ["Purchased"]]

y.head()

,Purchased
0,No
1,Yes
2,No
3,No
4,Yes


# Etape 4

In [39]:
#train_test_split !
#test_size = entre 20% et 30% de mes données vont aller dans le test set
#random state = moyen pour fixer la méthode de choix aléatoires.
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

x_train.head()

,Country,Age,Salary
4,Germany,40.0,NaN
9,France,37.0,67000.0
1,Spain,27.0,48000.0
6,Spain,NaN,52000.0
7,France,48.0,79000.0


In [40]:
# notanumber
# gestion des valeurs manquantes
# créer des instances de classes = je dis que ma stratégie est de remplacer par "médiane"
# une classe commence par une lettre en MAJ, soit SimpleImputer = classe
# une fonction est en min, comme imputer

imputer=SimpleImputer(strategy="median")
imputer


SimpleImputer(strategy='median')

In [41]:
#j'applique ma classe sur les données = fit.transform
# je transforme mes valeurs
imputer.fit_transform(x_train.iloc[:,1:])

array([[4.0e+01, 6.1e+04],
       [3.7e+01, 6.7e+04],
       [2.7e+01, 4.8e+04],
       [3.8e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [3.8e+01, 6.1e+04],
       [4.4e+01, 7.2e+04],
       [3.5e+01, 5.8e+04]])

In [42]:
x_train.iloc[:,1:]=imputer.fit_transform(x_train.iloc[:,1:])
x_train.head()
#mes valeurs NaN sont remplacés par la médiane

,Country,Age,Salary
4,Germany,40.0,61000.0
9,France,37.0,67000.0
1,Spain,27.0,48000.0
6,Spain,38.0,52000.0
7,France,48.0,79000.0


In [43]:
#Scaling & encoding
# créer un mini pipeline - mes données passent d'abord par sklearn puis encodeur
# je défini numeric fetaure = liste d'index de colonnes. j'ai des valeurs numériques dans colonnes 14 et 2

numeric_features=[1,2]
numeric_transformer= StandardScaler()

#pour mes variables catégorielles
categorical_features = [0]
categorical_transformer = OneHotEncoder ()

#le fait de mettre ma classe (par exemple, StandardScaler() sans rien entre les () = j'applique les paramètres par défaut à ma classe)

#création pipeline pré-processing =column transformer
#je transforme mes colonnes en 2 fonctionnalités. fonctionnalité catégorielle et fonctionnalité numérique.
#ces 2 transformers prennent la forme de tupples en fonction du nb de transformer que l'on aura.
feature_encoder = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features),
         #ce que prend le tupple = peut prendre n'importe quel nom, nommer le transformer auquel cela correspond, sur quelle colonne cela s'applique
        ('num', numeric_transformer, numeric_features)
    ]
)

#il faut que j'assigne sur x_train

x_train=feature_encoder.fit_transform(x_train)
x_train

array([[ 0.        ,  1.        ,  0.        ,  0.27978024, -0.13108063],
       [ 1.        ,  0.        ,  0.        , -0.23673712,  0.49810638],
       [ 0.        ,  0.        ,  1.        , -1.95846165, -1.49431914],
       [ 0.        ,  0.        ,  1.        , -0.06456467, -1.07486114],
       [ 1.        ,  0.        ,  0.        ,  1.65715986,  1.75648039],
       [ 0.        ,  0.        ,  1.        , -0.06456467, -0.13108063],
       [ 1.        ,  0.        ,  0.        ,  0.96847005,  1.02242888],
       [ 1.        ,  0.        ,  0.        , -0.58108203, -0.44567413]])

In [ ]:
#j'ai bien une nouvelle matrice avec mes nouvelles valeurs

• OneHotEncoder
Transforme mes variables catégorielles en variables nominales

• standard scaler
j'ai appliquer la même échelle à l'ensembe de mes valeurs numériques et appliquant un z-score
j'ai normalisé chacune des colonnes
mes valeurs sont donc comparables

In [44]:
y

,Purchased
0,No
1,Yes
2,No
3,No
4,Yes
5,Yes
6,No
7,Yes
8,No
9,Yes


In [46]:
#y encoding
label_encoder=LabelEncoder()

y_train=y_train.copy()
y_train=label_encoder.fit_transform(y_train)

y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [ ]:
####### TRAINING ######

In [47]:
x_test

,Country,Age,Salary
2,Germany,30.0,54000.0
8,Germany,50.0,83000.0


In [48]:
x_train

array([[ 0.        ,  1.        ,  0.        ,  0.27978024, -0.13108063],
       [ 1.        ,  0.        ,  0.        , -0.23673712,  0.49810638],
       [ 0.        ,  0.        ,  1.        , -1.95846165, -1.49431914],
       [ 0.        ,  0.        ,  1.        , -0.06456467, -1.07486114],
       [ 1.        ,  0.        ,  0.        ,  1.65715986,  1.75648039],
       [ 0.        ,  0.        ,  1.        , -0.06456467, -0.13108063],
       [ 1.        ,  0.        ,  0.        ,  0.96847005,  1.02242888],
       [ 1.        ,  0.        ,  0.        , -0.58108203, -0.44567413]])

In [49]:
#valeurs manquantes
x_test.iloc[:,1:]= imputer.transform(x_test.iloc[:,1:])
#transform et pas fit transform car déjà fait sur x_train

In [50]:
#encodong &scaling
x_test=feature_encoder.transform(x_test)
x_test

array([[ 0.        ,  1.        ,  0.        , -1.44194429, -0.86513213],
       [ 0.        ,  1.        ,  0.        ,  2.00150476,  2.1759384 ]])

In [55]:
y_test=y_test.copy()

In [57]:
#y_test preprocessing
y_test=label_encoder.transform(y_test)
y_test

array([0, 0], dtype=int64)

In [ ]:
"""il faut dissocier fit/transform et fit transform
pour x test que transform
fit calcule données sur train
transform = je l'applique à un autre jeu de données"""

algorithme regression linéaire
